# title: Sakshi Rathi
# logo: /assets/img/edit5.png
# description: text below image
# show_downloads: true
# theme: jekyll-theme-minimal

# Site configuration
title: "Sakshi Rathi's Portfolio"
description: "Data Scientist | Data Analyst | Machine Learning Enthusiast"
url: "https://sakshiiiir.github.io"  # URL for GitHub Pages
baseurl: "/portfolio"  # Adjust this to match your repo name on GitHub Pages

# Author information
author:
  name: "Sakshi Rathi"
  email: "sakshi.k.rathi@gmail.com"
  social:
    linkedin: "https://www.linkedin.com/in/sakshi-k-rathi/"
    github: "https://github.com/sakshiiiir"

# Theme settings
theme: jekyll-theme-minimal  # You can choose a theme that suits your style

# Navigation settings
nav:
  - title: "Home"
    url: "{{ site.baseurl }}/"
  - title: "Data Analytics"
    url: "{{ site.baseurl }}/data-analytics.md"
  - title: "Data Visualization"
    url: "{{ site.baseurl }}/data-visualization.md"
  - title: "Machine Learning"
    url: "{{ site.baseurl }}/machine-learning.md"
  - title: "Deep Learning"
    url: "{{ site.baseurl }}/deep-learning.md"
  - title: "Certifications"
    url: "{{ site.baseurl }}/certifications.md"

# Additional settings
show_excerpts: true  # Show excerpts on the homepage
paginate: 5  # Number of items per page in lists

# Theme settings for dark mode
theme_settings:
  dark_mode: true  # Enables dark mode if supported by the theme
